name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create dist folder if not exists
        run: |
          New-Item -ItemType Directory -Force -Path dist
        shell: pwsh

      - name: Generate snake.svg
        run: |
          $url = "https://gh-palette.snk.platane.io/svg-only?user=${{ github.repository_owner }}&palette=github-dark"
          Invoke-WebRequest -Uri $url -OutFile "dist/snake.svg"
        shell: pwsh

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
